# Generated by Django 2.2.19 on 2021-03-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": [("app_admin", "App adminitration permission")]},
        ),
    ]
