# Generated by Django 2.2.19 on 2021-03-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_reservation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="date",
            new_name="reservation_date",
        ),
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("room", "reservation_date")},
        ),
    ]
